# This is a basic workflow to help you get started with Actions

name: CompilePublish

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Clone BOSL
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'v1.0.3'
          owner: 'revarbat'
          repository: 'BOSL'

      - name: Debug
        run: |
          ./compile.sh Spool-Weight.scad
          ls output

      # # Runs a single command using the runners shell
      # - name: Setup BOSL
      #   run: setup.sh

      # # Runs a set of commands using the runners shell
      # - name: Compile
      #   run: compile.sh Spool-Weight.scad