name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master
  # push:
  #   tags:
  #     - "v*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Clone BOSL
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'v1.0.3'
        owner: 'revarbat'
        repository: 'BOSL'
    - name: Compile
      run: |
        ./compile.sh Spool-Weight.scad
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
    - name: Tag New Version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        custom_tag: ${{ steps.date.outputs.date }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "v${{ steps.date.outputs.date }}"
        files: |
          Spool-Weight-${{ steps.date.outputs.date }}.scad