name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Clone BOSL
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'v1.0.3'
        owner: 'revarbat'
        repository: 'BOSL'
    - name: Compile
      run: |
        ./compile.sh Spool-Weight.scad
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          Spool-Weight-${{ steps.date.outputs.date }}.scad
