# This is a basic workflow to help you get started with Actions

name: CompilePublish

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      publish_release:
        description: "Publish the build output"
        required: true
        default: 'false'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Clone BOSL
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'v1.0.3'
          owner: 'revarbat'
          repository: 'BOSL'

      - name: Get current date
        id: date
        run: echo "date=:$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Debug
        run: |
          echo ${{ steps.date.outputs.date }}

      # - name: Debug
      #   run: |
      #     ./compile.sh Spool-Weight.scad
      #     ls output

      # - if: github.event.inputs.publish_release == 'true'
      #   run: |
      #     echo "running publish"

      # - name: Create Release
      #   id: create_release
      #   uses: comnoco/create-release@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Changes in this Release
      #       - First Change
      #       - Second Change
      #     draft: false
      #     prerelease: false
