name: Tag New Version
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
    - name: Tag New Version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        custom_tag: v${{ steps.date.outputs.date }}
        github_token: ${{ secrets.GITHUB_TOKEN }}